EasyStay.Web/Controllers/VillaController.cs
using EasyStay.Application.Common.Interfaces;
using EasyStay.Domain.Entities;
using EasyStay.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;

namespace EasyStay.Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var villas = _unitOfWork.Villa.GetAll();
            return View(villas);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Villa obj)
        {
            
            if (ModelState.IsValid)
            {
                if(obj.Image is not null)
                {
                    var imageName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(_webHostEnvironment.WebRootPath, @"images\Villas");
                    var extension = Path.GetExtension(obj.Image.FileName);

                    if (!Directory.Exists(uploads))
                        Directory.CreateDirectory(uploads);

                    using (var fileStreams = new FileStream(Path.Combine(uploads, imageName + extension), FileMode.Create))
                    {
                        obj.Image.CopyTo(fileStreams);
                    }
                    obj.ImageUrl = @"\images\Villas\" + imageName + extension;
                }
                else
                {
                    obj.ImageUrl = "https://placehold.co/600x400";
                }

                _unitOfWork.Villa.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "The villa has been created successfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The villa can't be created";
            return View(obj);
        }
        [HttpGet]
        public IActionResult Update(int villaId)
        {
            Villa? villa = _unitOfWork.Villa.Get(u => u.Id == villaId);
            if (villa is null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villa);
        }
        [HttpPost]
        public IActionResult Update(Villa obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Image is not null)
                {
                    var imageName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(_webHostEnvironment.WebRootPath, @"images\Villas");
                    var extension = Path.GetExtension(obj.Image.FileName);

                    if (!Directory.Exists(uploads))
                        Directory.CreateDirectory(uploads);

                    if (obj.ImageUrl is not null)
                    {
                        var oldFilePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldFilePath))
                            System.IO.File.Delete(oldFilePath);
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads, imageName + extension), FileMode.Create))
                    {
                        obj.Image.CopyTo(fileStreams);
                    }
                    obj.ImageUrl = @"\images\Villas\" + imageName + extension;
                }
                else
                {
                    if (obj.ImageUrl is null)
                        obj.ImageUrl = "https://placehold.co/600x400";
                }
                _unitOfWork.Villa.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "The villa has been updated successfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The villa can't be updated";
            return View(obj);
        }
        [HttpGet]
        public IActionResult Delete(int villaId)
        {
            Villa? villa = _unitOfWork.Villa.Get(u => u.Id == villaId);
            if (villa is null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villa);
        }
        [HttpPost]
        public IActionResult Delete(Villa obj)
        {
            Villa? villaFromDb = _unitOfWork.Villa.Get(v => v.Id == obj.Id);

            if (villaFromDb is not null)
            {
                if (villaFromDb.ImageUrl is not null)
                {
                    var filePath = Path.Combine(_webHostEnvironment.WebRootPath, villaFromDb.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(filePath))
                        System.IO.File.Delete(filePath);
                }
                _unitOfWork.Villa.Remove(villaFromDb);
                _unitOfWork.Save();
                TempData["success"] = "The villa has been deleted successfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The villa can't be deleted";
            return View(obj);
        }
    }
}

EasyStay.Web/Views/Villa/Create.cshtml
@model Villa;

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success m-lg-0 py-3">
        <div class="col-12 text-center">
            <h2 class="text-white">Create Villa</h2>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Price" class="form-control border shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Sqft" class="form-control border shadow" />
                    <label asp-for="Sqft" class="ms-2"></label>
                    <span asp-validation-for="Sqft" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Occupancy" class="form-control border shadow" />
                    <label asp-for="Occupancy" class="ms-2"></label>
                    <span asp-validation-for="Occupancy" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Image" class="form-control border shadow" type="file" id="Image" />
                    <input asp-for="ImageUrl" class="form-control border shadow" hidden/>
                    <label asp-for="ImageUrl" class="ms-2"></label>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="villa" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

EasyStay.Web/Views/Villa/Delete.cshtml
@model Villa;

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success m-lg-0 py-3">
        <div class="col-12 text-center">
            <h2 class="text-white">Delete Villa</h2>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="col-10">
                <div class="p-3">
                    @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Name" class="form-control border shadow" disabled />
                        <label asp-for="Name" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Description" class="form-control border shadow" disabled />
                        <label asp-for="Description" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Price" class="form-control border shadow" disabled />
                        <label asp-for="Price" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Sqft" class="form-control border shadow" disabled />
                        <label asp-for="Sqft" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Occupancy" class="form-control border shadow" disabled />
                        <label asp-for="Occupancy" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="ImageUrl" class="form-control border shadow" disabled hidden />
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-danger w-100">
                                <i class="bi bi-trash-fill"></i> Delete
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="villa" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%" style="border-radius:5px; border:1px solid #bbb9b9" alt="Villa Image" />
            </div>
            
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

EasyStay.Web/Views/Villa/Index.cshtml
@model IEnumerable<EasyStay.Domain.Entities.Villa>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success m-lg-0 py-3">
        <div class="col-12 text-center">
            <h2 class="text-white">Villa List</h2>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Villa" asp-action="Create" class="btn btn-secondary"><i class="bi bi-plus-circle"></i> Create New villa</a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Sqft</th>
                    <th>Occupancy</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var villa in Model)
                {
                    <tr>
                        <td>@villa.Name</td>
                        <td>@villa.Price</td>
                        <td>@villa.Sqft</td>
                        <td>@villa.Occupancy</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Villa" asp-action="Update" asp-route-villaId="@villa.Id" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Villa" asp-action="Delete" asp-route-villaId="@villa.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

EasyStay.Web/Views/Villa/Update.cshtml
@model Villa;

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success m-lg-0 py-3">
        <div class="col-12 text-center">
            <h2 class="text-white">Update Villa</h2>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="col-10">
                <div class="p-3">
                    @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Name" class="form-control border shadow" />
                        <label asp-for="Name" class="ms-2"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Description" class="form-control border shadow" />
                        <label asp-for="Description" class="ms-2"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Price" class="form-control border shadow" />
                        <label asp-for="Price" class="ms-2"></label>
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Sqft" class="form-control border shadow" />
                        <label asp-for="Sqft" class="ms-2"></label>
                        <span asp-validation-for="Sqft" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Occupancy" class="form-control border shadow" />
                        <label asp-for="Occupancy" class="ms-2"></label>
                        <span asp-validation-for="Occupancy" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Image" class="form-control border shadow" type="file" id="Image" />
                        <input asp-for="ImageUrl" class="form-control border shadow" hidden />
                        <label asp-for="ImageUrl" class="ms-2"></label>
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <i class="bi bi-check-circle"></i> Update
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="villa" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%" style="border-radius:5px; border:1px solid #bbb9b9" alt="Villa Image" />
            </div>
            
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}